### ISSUE TITLE
Global CSS should fall back to ssr?

### ISSUE THREAD

**Issue by Aidurber** [nuxt/adonuxt#1]
Sorry if the title makes no sense. I've just made a fresh project and hit the page. main.css is loaded slowly, and the page us unstyled for a moment then main.css is loaded. The below gif should highlight what I mean better than I can explain.

![adonuxt](https://cloud.githubusercontent.com/assets/5732291/21839649/cda57324-d7d0-11e6-9080-772c22e427dd.gif)

**config/nuxt.js**
```javascript
  /*
  ** Global CSS
  */
  css: ['~assets/css/main.css'],
```

Is it possible to load in the global CSS file earlier?

**Comment by Atinux** [comment]
Hi @Aidurber 

This is because the CSS is in the JavaScript build on **development mode** to allow hot-reloading via Webpack.

In production, the CSS is separated and put in the header so this "flash" does not appear anymore.

Here an example in production:
![adonuxt](https://cloud.githubusercontent.com/assets/904724/21840054/8659b6f0-d7db-11e6-8225-48bb806a0574.gif)

You can see it when doing:
```bash
npm run build && npm start
```

**Comment by Aidurber** [comment]
Sorry @Atinux, just read the source code and came to the same conclusion. Came back to close this issue. 
Thanks for the speedy response 😄
